version: "3"

services:
  kerberos_server:
    image: omvk97/kerberos
    container_name: kerberos
    ports:
      - 88:88 # The ports the kdc server listens on
      - 3000:3000 # The API port to create and read keytabs
    environment:
      KERBEROS_ADMIN_PW: password
      KERBEROS_HOST_DNS: localhost
      KERBEROS_REALM: KAFKA.SECURE
      KERBEROS_API_PORT: 3000
      KERBEROS_MSSQL_CONNECTION_STRING: "Server=172.19.0.1;Database=master;User Id=sa;Password=Database_password1;"